-- Supabase SQL Editor에 전체 실행
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  category text not null default 'free',
  title text not null,
  content text not null,
  author text,
  link_url text,
  views integer not null default 0,
  is_notice boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 기존 댓글 테이블이 있다면 삭제 (댓글 기능 제거)
drop table if exists public.comments cascade;

alter table public.posts enable row level security;

-- 관리자 여부 확인 함수 (app_metadata의 role이 admin인지 확인)
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select coalesce((auth.jwt()->'app_metadata'->>'role')='admin', false);
$$;

-- RLS 정책 재설정
drop policy if exists "posts_read" on public.posts;
drop policy if exists "posts_insert" on public.posts;
drop policy if exists "posts_insert_admin" on public.posts;
drop policy if exists "posts_update_admin" on public.posts;
drop policy if exists "posts_delete_admin" on public.posts;

-- 1. 조회: 누구나 가능 (비로그인, 로그인 모두)
create policy "posts_read" on public.posts
  for select to anon, authenticated using (true);

-- 2. 글쓰기: 관리자만 가능
create policy "posts_insert_admin" on public.posts
  for insert to authenticated with check (public.is_admin());

-- 3. 수정: 관리자만 가능
create policy "posts_update_admin" on public.posts
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- 4. 삭제: 관리자만 가능
create policy "posts_delete_admin" on public.posts
  for delete to authenticated using (public.is_admin());

-- 조회수 증가 RPC 함수 (누구나 실행 가능)
create or replace function public.increment_post_views(post_id bigint)
returns void language sql security definer set search_path=public as $$
  update public.posts set views = views + 1 where id = post_id;
$$;
grant execute on function public.increment_post_views(bigint) to anon, authenticated;

-- 수정일자 갱신 트리거
create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists posts_updated_at on public.posts;
create trigger posts_updated_at before update on public.posts for each row execute function public.set_updated_at();
